from enum import Enum

class Operation(str, Enum):
    PAUSED_BY_OWNER='PAUSED_BY_OWNER'; RUNNING='RUNNING'; INCIDENT_HOLD='INCIDENT_HOLD'; WINDING_DOWN='WINDING_DOWN'
class Autonomy(str, Enum):
    DESIGN_ONLY='DESIGN_ONLY'; DRY_RUN='DRY_RUN'; ASSISTED_ONLY='ASSISTED_ONLY'; BOUNDED_LIVE='BOUNDED_LIVE'
class ActionState(str, Enum):
    PROPOSED='PROPOSED'; READY='READY'; AUTHORIZED='AUTHORIZED'; RUNNING='RUNNING'; SUCCEEDED='SUCCEEDED'; BLOCKED='BLOCKED'; FAILED='FAILED'; CANCELLED='CANCELLED'; UNKNOWN_OUTCOME='UNKNOWN_OUTCOME'
class CapabilityStatus(str, Enum):
    EXPOSED='EXPOSED'; AUTHENTICATED='AUTHENTICATED'; READ_VERIFIED='READ_VERIFIED'; WRITE_SANDBOX_VERIFIED='WRITE_SANDBOX_VERIFIED'; LIVE_VERIFIED='LIVE_VERIFIED'; DEGRADED='DEGRADED'; BLOCKED='BLOCKED'
